name: 'Deploy to Dropbox'
description: 'This action will handle the deployment process of your project to Dropbox.'
author: 'aTable'
branding:
  icon: 'upload-cloud'
  color: 'black'
runs:
  using: 'node12'
  main: 'dist/index.js'
inputs:
  DROPBOX_ACCESS_TOKEN:
    description: 'Value should be a secret that is set in your repository settings'
    required: true

  GLOB: 
    description: 'Glob that you want to save to Dropbox e.g dir1/dir2/**/*.md or **/*.txt'
    required: true
  
  DROPBOX_DESTINATION_PATH_PREFIX:
    description: 'The destination path prefix to save to in Dropbox. This will prepend the individual globs. Default value is "/"'
    required: false
    default: "/"

  FILE_WRITE_MODE:
    description: 'Set file write mode when conflict occurs. Allowed modes: "add", "overwrite", "update"'
    required: false
    default: "add"

