on: [push]

jobs:
  local_development:
    runs-on: ubuntu-latest
    name: Testing action
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test Dropbox Upload
        uses: ./ # Uses an action in the root directory
        with:
          DROPBOX_ACCESS_TOKEN: ${{ secrets.DROPBOX_ACCESS_TOKEN }}
          DROPBOX_DESTINATION_PATH_PREFIX: "/"
          GLOB: "sample/**/*.md"
